# Proactical Machine Learning Prediction Assignment

##Libraries
I used the following packages not listed in the course materials:
randomForest package because the caret package run times were extremely long.
http://cran.r-project.org/web/packages/randomForest/randomForest.pdf
 
I used the doParallel and foreach to speed up my 
http://cran.r-project.org/web/packages/doParallel/vignettes/gettingstartedParallel.pdf

'''
library(Hmisc)
library(caret)
library(randomForest)
library(foreach)
library(doParallel)
set.seed(998)
options(warn=-1)
'''

## Loading Training Data
The pml-training.csv data is actually used to devise training and testing sets.
The pml-test.csv data is used to predict and answer the 20 questions based on the trained model.
'''
training.file   <- 'pml-training.csv'
test.cases.file <- 'pml-test.csv'
training.url    <- 'http://d396qusza40orc.cloudfront.net/predmachlearn/pml-training.csv'
test.cases.url  <- 'http://d396qusza40orc.cloudfront.net/predmachlearn/pml-testing.csv'
'''

download.file(training.url, training.file)
download.file(test.cases.url,test.cases.file )

## Cleaning Data
First all blank('""'), '#DIV/0' and 'NA' values are converted to 'NA'.
Any Columns containing 'NA' are removed from both downloaded data sets.
'''
training.df   <-read.csv(training.file, na.strings=c("NA","#DIV/0!", ""))
test.cases.df <-read.csv(test.cases.file , na.strings=c("NA", "#DIV/0!", ""))
training.df<-training.df[,colSums(is.na(training.df)) == 0]
test.cases.df <-test.cases.df[,colSums(is.na(test.cases.df)) == 0]
'''

The features user_name raw_timestamp_part_1 raw_timestamp_part_2   cvtd_timestamp new_window num_window are not related
to calculations and are removed form the downloaded data.
'''
 training.df   <-training.df[,-c(1:7)]
 test.cases.df <-test.cases.df[,-c(1:7)]
 '''

##Create a stratified random sample of the data into training and test sets.seed(998)
inTraining.matrix    <- createDataPartition(training.df$classe, p = 0.75, list = FALSE)
training.data.df <- training.df[inTraining.matrix, ]
testing.data.df  <- training.df[-inTraining.matrix, ]

## Use Random Forests 
The outcome variable is 'classe'
All variables other variables that assist in determining classe are defined as 'variables'.
The outcome variable is 'classe'are "fit' 
'''
registerDoParallel()
classe <- training.data.df$classe
variables <- training.data.df[-ncol(training.data.df)]

rf <- foreach(ntree=rep(250, 5), .combine=randomForest::combine, .packages='randomForest') %dopar% {
randomForest(variables, classe, ntree=ntree) 
}
''

#Confusion Matrix for Training
training.predictions <- predict(rf, newdata=training.data.df)
confusionMatrix(training.predictions,training.data.df$classe)
Confusion Matrix and Statistics

          Reference
Prediction    A    B    C    D    E
         A 4185    0    0    0    0
         B    0 2848    0    0    0
         C    0    0 2567    0    0
         D    0    0    0 2412    0
         E    0    0    0    0 2706

Overall Statistics
                                     
               Accuracy : 1          
                 95% CI : (0.9997, 1)
    No Information Rate : 0.2843     
    P-Value [Acc > NIR] : < 2.2e-16  
                                     
                  Kappa : 1          
 Mcnemar's Test P-Value : NA    
 
 Statistics by Class:

                     Class: A Class: B Class: C Class: D Class: E
Sensitivity            1.0000   1.0000   1.0000   1.0000   1.0000
Specificity            1.0000   1.0000   1.0000   1.0000   1.0000
Pos Pred Value         1.0000   1.0000   1.0000   1.0000   1.0000
Neg Pred Value         1.0000   1.0000   1.0000   1.0000   1.0000
Prevalence             0.2843   0.1935   0.1744   0.1639   0.1839
Detection Rate         0.2843   0.1935   0.1744   0.1639   0.1839
Detection Prevalence   0.2843   0.1935   0.1744   0.1639   0.1839
Balanced Accuracy      1.0000   1.0000   1.0000   1.0000   1.0000



#Confusion Matrix for testing 
testing.predictions <- predict(rf, newdata=testing.data.df)
confusionMatrix(testing.predictions,testing.data.df$classe)

Confusion Matrix and Statistics

          Reference
Prediction    A    B    C    D    E
         A 1394    5    0    0    0
         B    0  943    8    0    0
         C    0    1  845    5    0
         D    0    0    2  799    2
         E    1    0    0    0  899

Overall Statistics
                                          
               Accuracy : 0.9951          
                 95% CI : (0.9927, 0.9969)
    No Information Rate : 0.2845          
    P-Value [Acc > NIR] : < 2.2e-16       
                                          
                  Kappa : 0.9938          
 Mcnemar's Test P-Value : NA              

Statistics by Class:

                     Class: A Class: B Class: C Class: D Class: E
Sensitivity            0.9993   0.9937   0.9883   0.9938   0.9978
Specificity            0.9986   0.9980   0.9985   0.9990   0.9998
Pos Pred Value         0.9964   0.9916   0.9929   0.9950   0.9989
Neg Pred Value         0.9997   0.9985   0.9975   0.9988   0.9995
Prevalence             0.2845   0.1935   0.1743   0.1639   0.1837
Detection Rate         0.2843   0.1923   0.1723   0.1629   0.1833
Detection Prevalence   0.2853   0.1939   0.1735   0.1637   0.1835
Balanced Accuracy      0.9989   0.9958   0.9934   0.9964   0.9988


#Coursera provided code for submission

pml_write_files = function(x){
  n = length(x)
  for(i in 1:n){
    filename = paste0("problem_id_",i,".txt")
    write.table(x[i],file=filename,quote=FALSE,row.names=FALSE,col.names=FALSE)
  }
}


x <- evaluation_data
x <- x[feature_set[feature_set!='classe']]
answers <- predict(rf, newdata=x)

answers

pml_write_files(answers)
